# Copyright (c) 2022 Joshua Schmitt
# 
# This software is released under the MIT License.
# https://opensource.org/licenses/MIT

github: [ jqshuv ]
ko_fi: jqshuv
custom: [ 'https://tinu.be/jqshuvZap' ]
